name: Hello

on:
    schedule:
        - cron: '*/5 * * * *'

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
        - name: say hello to users
          run: echo "Hello to everyone"
