name: matrix build

on: 
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy: 
            
            matrix:
                os: [ windows-latest , macos-latest ]
                pyhton-version: ["3.10","3.11","3.12"]
                exclude:
                    - os: windows-latest 
                      pyhton-version: "3.10" 

        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.pyhton-version }}
            
            - name: Print Python version
              run: echo "python --version"