name: Secrets

on: 
    workflow_dispatch:



jobs:
    check-secret:
        runs-on: ubuntu-latest
        steps:
            - name: Check Secret
              run: |
                if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
                  echo "The secret is set: true"
                else
                  echo "The secret is set: false"
                fi

    print-secret:
        runs-on: ubuntu-latest
        steps:
            - name: Print Secret
              env:
                msg: ${{secrets.MY_SECRET_MESSAGE}}
              #run: echo "Secret is ${{secrets.MY_SECRET_MESSAGE}}"
              run: echo "Secret is $msg"
