name: Self Hosted Runner

on:
    workflow_dispatch:

jobs:
    Tasks:
        runs-on: [self-hosted, my-linux-runner]
        steps:
            - name: Print the hostname of the machine 
              run: |
                echo "Machine Hostname is:"
                hostname


            - name: Print the working directory
              run:  echo "Working Directory is ${{github.workspace}}"

            - name: Create File
              run: echo "Hello from GitHub Actions" > test-file.txt