name: Run Tests

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Run Tests
              run: |
                echo "Running the Test ..."
                echo "Test Succesfull"
